# acitve spring boot profile
spring:
   profiles:
      active: dev

---
# common spring boot configuration
spring:
   #MVC
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   #http
   http:
      encoding:
         charset: UTF-8
         enabled: true
         forced: true
         forced-request: true
         forced-response: true

   #message resource(Internationalization)
   messages:
      always-message-format: true
      basename: messages/messages_ko
      encoding: UTF-8

   #multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB
   
   #AOP
   aop:
      auto: true
      proxy-target-class: true

---
# dev profile - spring boot configuration
spring:
   profiles: dev
   # devtools enabled
   devtools: 
      livereload:
         enabled: true

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.80.114:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb
      initialSize: 10
      maxActive: 100        


---
# production profile - spring boot configuration
spring:
   profiles: production


   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.80.114:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb
      initialSize: 10
      maxActive: 100 


---
# server
server:
   port: 8081
   servlet: 
      context-path: /mysite06



---
#mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml


---
#logging
logging:
   config: classpath:logback.xml
