# acitve spring boot profile
spring:
   profiles:
      active: dev

---
# common spring boot configuration




---
# dev profile - spring boot configuration
spring:
   profiles: dev
       


---
# production profile - spring boot configuration
spring:
   profiles: production




---
# server
